const mongoose = require('mongoose');
const Plant = require('../models/Plant');
require('dotenv').config();

const plantData = [
    {
        name: "Monstera Deliciosa",
        scientificName: "Monstera deliciosa",
        categoryGroup: "Indoor & Outdoor",
        category: "Indoor",
        description: "A stunning tropical plant with large, heart-shaped leaves featuring distinctive holes. Perfect for indoor decoration and air purification.",
        price: 1299,
        discountPrice: 999,
        stock: 25,
        image: "https://placehold.co/500x500?text=Monstera+Deliciosa",
        height: "60-80 cm",
        potSize: "8 inch",
        sunlight: "Partial Sun",
        watering: "Every 10-15 days",
        temperature: "18-29°C",
        fertilizer: "Balanced fertilizer monthly",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.5,
    },
    {
        name: "Snake Plant",
        scientificName: "Sansevieria trifasciata",
        categoryGroup: "Indoor & Outdoor",
        category: "Indoor",
        description: "A hardy and low-maintenance succulent plant that thrives in various light conditions. Excellent air purifier for homes.",
        price: 599,
        discountPrice: 449,
        stock: 40,
        image: "https://placehold.co/500x500?text=Snake+Plant",
        height: "40-50 cm",
        potSize: "6 inch",
        sunlight: "Partial Sun",
        watering: "Every 2-3 weeks",
        temperature: "16-27°C",
        fertilizer: "Minimal fertilizer needed",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.7,
    },
    {
        name: "Pothos",
        scientificName: "Epipremnum aureum",
        categoryGroup: "Garden & Balcony",
        category: "Hanging Plant",
        description: "A versatile vining plant with heart-shaped leaves. Grows quickly and is perfect for hanging baskets or shelves.",
        price: 399,
        discountPrice: 299,
        stock: 50,
        image: "https://placehold.co/500x500?text=Pothos",
        height: "30-40 cm",
        potSize: "5 inch",
        sunlight: "Partial Sun",
        watering: "Every 10-15 days",
        temperature: "20-25°C",
        fertilizer: "Monthly diluted fertilizer",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.6,
    },
    {
        name: "Aloe Vera",
        scientificName: "Aloe barbadensis",
        categoryGroup: "Specialty Plants",
        category: "Succulent",
        description: "A medicinal succulent plant with gel-filled leaves. Low maintenance and perfect for windowsills.",
        price: 299,
        discountPrice: 199,
        stock: 60,
        image: "https://placehold.co/500x500?text=Aloe+Vera",
        height: "20-30 cm",
        potSize: "4 inch",
        sunlight: "Full Sun",
        watering: "Every 2-3 weeks",
        temperature: "18-27°C",
        fertilizer: "Minimal fertilizer",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.8,
    },
    {
        name: "Areca Palm",
        scientificName: "Dypsis lutescens",
        categoryGroup: "Indoor & Outdoor",
        category: "Indoor",
        description: "An elegant tropical palm that adds a lush, tropical feel to any indoor space. Great for creating natural ambiance.",
        price: 1599,
        discountPrice: 1299,
        stock: 15,
        image: "https://placehold.co/500x500?text=Areca+Palm",
        height: "90-120 cm",
        potSize: "10 inch",
        sunlight: "Partial Sun",
        watering: "Daily",
        temperature: "18-29°C",
        fertilizer: "Monthly during growing season",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.4,
    },
    {
        name: "Spider Plant",
        scientificName: "Chlorophytum comosum",
        categoryGroup: "Garden & Balcony",
        category: "Hanging Plant",
        description: "A resilient plant known for its air-purifying properties. Produces adorable baby plantlets perfect for propagation.",
        price: 349,
        discountPrice: 249,
        stock: 45,
        image: "https://placehold.co/500x500?text=Spider+Plant",
        height: "25-35 cm",
        potSize: "5 inch",
        sunlight: "Partial Sun",
        watering: "Every 10-15 days",
        temperature: "15-25°C",
        fertilizer: "Light fertilizer monthly",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.7,
    },
    {
        name: "Fiddle Leaf Fig",
        scientificName: "Ficus lyrata",
        categoryGroup: "Indoor & Outdoor",
        category: "Indoor",
        description: "A statement plant with large, violin-shaped leaves. Brings drama and elegance to modern interiors.",
        price: 2499,
        discountPrice: 1999,
        stock: 10,
        image: "https://placehold.co/500x500?text=Fiddle+Leaf+Fig",
        height: "100-150 cm",
        potSize: "12 inch",
        sunlight: "Partial Sun",
        watering: "Weekly",
        temperature: "18-27°C",
        fertilizer: "Monthly during growing season",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.5,
    },
    {
        name: "Jade Plant",
        scientificName: "Crassula ovata",
        categoryGroup: "Specialty Plants",
        category: "Succulent",
        description: "A compact succulent with plump, jade-green leaves. Symbol of good luck and prosperity.",
        price: 699,
        discountPrice: 499,
        stock: 30,
        image: "https://placehold.co/500x500?text=Jade+Plant",
        height: "40-50 cm",
        potSize: "6 inch",
        sunlight: "Full Sun",
        watering: "Every 2-3 weeks",
        temperature: "15-25°C",
        fertilizer: "Light feeding in spring/summer",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.6,
    },
    {
        name: "Peace Lily",
        scientificName: "Spathiphyllum wallisii",
        categoryGroup: "Indoor & Outdoor",
        category: "Indoor",
        description: "An elegant plant with dark green leaves and white flowers. Excellent air purifier and low-light tolerant.",
        price: 799,
        discountPrice: 599,
        stock: 35,
        image: "https://placehold.co/500x500?text=Peace+Lily",
        height: "30-40 cm",
        potSize: "6 inch",
        sunlight: "Shade",
        watering: "Every 10-15 days",
        temperature: "18-29°C",
        fertilizer: "Monthly diluted fertilizer",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.5,
    },
    {
        name: "Boston Fern",
        scientificName: "Nephrolepis exaltata",
        categoryGroup: "Garden & Balcony",
        category: "Hanging Plant",
        description: "A classic fern with delicate, feathery fronds. Perfect for creating a lush, green ambiance.",
        price: 549,
        discountPrice: 399,
        stock: 20,
        image: "https://placehold.co/500x500?text=Boston+Fern",
        height: "30-45 cm",
        potSize: "6 inch",
        sunlight: "Partial Sun",
        watering: "Alternate days",
        temperature: "15-24°C",
        fertilizer: "Monthly during growing season",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.4,
    },
    {
        name: "Cactus Mix",
        scientificName: "Various species",
        categoryGroup: "Specialty Plants",
        category: "Cactus",
        description: "A collection of small cacti perfect for desk or shelf display. Minimal water requirements.",
        price: 299,
        discountPrice: 199,
        stock: 50,
        image: "https://placehold.co/500x500?text=Cactus+Mix",
        height: "10-15 cm",
        potSize: "3 inch",
        sunlight: "Full Sun",
        watering: "Every 2-3 weeks",
        temperature: "15-30°C",
        fertilizer: "Minimal fertilizer",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.3,
    },
    {
        name: "Orchid Elegance",
        scientificName: "Phalaenopsis hybrid",
        categoryGroup: "Specialty Plants",
        category: "Orchid",
        description: "A beautiful orchid with long-lasting exotic flowers. Perfect for adding sophistication to your space.",
        price: 1299,
        discountPrice: 999,
        stock: 18,
        image: "https://placehold.co/500x500?text=Orchid+Elegance",
        height: "25-35 cm",
        potSize: "5 inch",
        sunlight: "Partial Sun",
        watering: "Weekly",
        temperature: "18-25°C",
        fertilizer: "Orchid fertilizer bi-weekly",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.7,
    },
    {
        name: "Ficus Bonsai",
        scientificName: "Ficus retusa",
        categoryGroup: "Specialty Plants",
        category: "Bonsai",
        description: "A beautifully crafted bonsai tree that brings Zen to your space.",
        price: 2499,
        discountPrice: 1999,
        stock: 10,
        image: "https://placehold.co/500x500?text=Ficus+Bonsai",
        height: "20-30 cm",
        potSize: "6 inch",
        sunlight: "Full Sun",
        watering: "Alternate days",
        temperature: "15-25°C",
        fertilizer: "Bonsai fertilizer monthly",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.9,
    },
    {
        name: "Bougainvillea",
        scientificName: "Bougainvillea glabra",
        categoryGroup: "Indoor & Outdoor",
        category: "Outdoor",
        description: "A vibrant outdoor plant known for its bright, papery flowers.",
        price: 599,
        discountPrice: 499,
        stock: 30,
        image: "https://placehold.co/500x500?text=Bougainvillea",
        height: "50-100 cm",
        potSize: "8 inch",
        sunlight: "Full Sun",
        watering: "Weekly",
        temperature: "20-35°C",
        fertilizer: "Monthly",
        isIndoor: false,
        isOutdoor: true,
        rating: 4.6,
    },
    {
        name: "Peace Lily",
        scientificName: "Spathiphyllum",
        categoryGroup: "Garden & Balcony",
        category: "Flowering",
        description: "An elegant plant with white blooms that purifies the air.",
        price: 399,
        discountPrice: 349,
        stock: 25,
        image: "https://placehold.co/500x500?text=Peace+Lily",
        height: "30-50 cm",
        potSize: "6 inch",
        sunlight: "Partial Sun",
        watering: "Weekly",
        temperature: "18-25°C",
        fertilizer: "Bi-monthly",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.7,
    },
    {
        name: "Calathea Ornata",
        scientificName: "Calathea ornata",
        categoryGroup: "Garden & Balcony",
        category: "Foliage",
        description: "Known for its stunning pink-striped leaves, perfect for indoor decor.",
        price: 499,
        discountPrice: 399,
        stock: 20,
        image: "https://placehold.co/500x500?text=Calathea",
        height: "20-40 cm",
        potSize: "5 inch",
        sunlight: "Partial Sun",
        watering: "Weekly",
        temperature: "18-24°C",
        fertilizer: "Monthly",
        isIndoor: true,
        isOutdoor: false,
        rating: 4.5,
    },
    {
        name: "English Ivy",
        scientificName: "Hedera helix",
        categoryGroup: "Garden & Balcony",
        category: "Climbing Plant",
        description: "A vigorous climber with beautiful lobed leaves.",
        price: 299,
        discountPrice: 249,
        stock: 40,
        image: "https://placehold.co/500x500?text=English+Ivy",
        height: "50-100 cm",
        potSize: "6 inch",
        sunlight: "Partial Sun",
        watering: "Weekly",
        temperature: "10-21°C",
        fertilizer: "Monthly",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.4,
    },
    {
        name: "Tomato Plant",
        scientificName: "Solanum lycopersicum",
        categoryGroup: "Kitchen Garden",
        category: "Vegetable",
        description: "Grow your own fresh, juicy tomatoes at home.",
        price: 199,
        discountPrice: 149,
        stock: 50,
        image: "https://placehold.co/500x500?text=Tomato+Plant",
        height: "30-60 cm",
        potSize: "8 inch",
        sunlight: "Full Sun",
        watering: "Alternate days",
        temperature: "20-30°C",
        fertilizer: "Weekly",
        isIndoor: false,
        isOutdoor: true,
        rating: 4.8,
    },
    {
        name: "Lemon Tree (Dwarf)",
        scientificName: "Citrus limon",
        categoryGroup: "Kitchen Garden",
        category: "Fruit",
        description: "A compact fruit tree perfect for balconies.",
        price: 899,
        discountPrice: 799,
        stock: 15,
        image: "https://placehold.co/500x500?text=Lemon+Tree",
        height: "60-90 cm",
        potSize: "10 inch",
        sunlight: "Full Sun",
        watering: "Alternate days",
        temperature: "20-35°C",
        fertilizer: "Monthly citrus fertilizer",
        isIndoor: false,
        isOutdoor: true,
        rating: 4.6,
    },
    {
        name: "Sweet Basil",
        scientificName: "Ocimum basilicum",
        categoryGroup: "Kitchen Garden",
        category: "Herb",
        description: "A fragrant culinary herb essential for your kitchen garden.",
        price: 149,
        discountPrice: 99,
        stock: 60,
        image: "https://placehold.co/500x500?text=Sweet+Basil",
        height: "20-30 cm",
        potSize: "4 inch",
        sunlight: "Full Sun",
        watering: "Alternate days",
        temperature: "20-30°C",
        fertilizer: "Bi-weekly",
        isIndoor: true,
        isOutdoor: true,
        rating: 4.7,
    },
    {
        name: "Holy Basil (Tulsi)",
        scientificName: "Ocimum tenuiflorum",
        categoryGroup: "Kitchen Garden",
        category: "Medicinal",
        description: "A highly revered medicinal plant with numerous health benefits.",
        price: 199,
        discountPrice: 149,
        stock: 45,
        image: "https://placehold.co/500x500?text=Tulsi",
        height: "20-40 cm",
        potSize: "5 inch",
        sunlight: "Full Sun",
        watering: "Alternate days",
        temperature: "20-35°C",
        fertilizer: "Monthly",
        isIndoor: false,
        isOutdoor: true,
        rating: 4.9,
    },
    {
        name: "Sunflower Seeds",
        scientificName: "Helianthus annuus",
        categoryGroup: "Kitchen Garden",
        category: "Seeds",
        description: "High-quality seeds to grow your own bright sunflowers.",
        price: 99,
        discountPrice: 49,
        stock: 100,
        image: "https://placehold.co/500x500?text=Sunflower+Seeds",
        height: "N/A",
        potSize: "N/A",
        sunlight: "Full Sun",
        watering: "Daily",
        temperature: "20-30°C",
        fertilizer: "N/A",
        isIndoor: false,
        isOutdoor: true,
        rating: 4.5,
    }
];

const seedDatabase = async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGO_URI);
        console.log("Connected to MongoDB");

        // Clear existing plants
        await Plant.deleteMany({});
        console.log("Cleared existing plants");

        // Insert seed data
        const insertedPlants = await Plant.insertMany(plantData);
        console.log(`Successfully inserted ${insertedPlants.length} plants`);

        // Close the connection
        await mongoose.disconnect();
        console.log("Database connection closed");
        process.exit(0);
    } catch (error) {
        console.error("Error seeding database:", error);
        process.exit(1);
    }
};

seedDatabase();
